version: '3'

services:
  # nginx:
  #   image: nginx
  #   links:
  #     - app
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./docker/default.conf:/etc/nginx/conf.d/default.conf
  #     - ./public/:/usr/share/nginx/html/
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "20M"
  #       max-file: "10"
  app:
    image: phpswoole/swoole
    environment:
      AUTORELOAD_PROGRAMS: "swoole"
      AUTORELOAD_ANY_FILES: 1
      SERVER_NAME: "$SERVER_NAME"
    volumes:
      - ./app:/var/www
      - ./public/:/var/html
      - ./storage:/var/data
      - ./config:/var/config
      - ./php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini
    ports:
      - 80:9501
    logging:
      driver: "json-file"
      options:
        max-size: "20M"
        max-file: "10"
